# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flashcards.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class UiModuleFlashcards(object):
    def setupUi(self, moduleFlashcards):
        moduleFlashcards.setObjectName("moduleFlashcards")
        moduleFlashcards.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(moduleFlashcards)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 500, 83, 25))
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 50, 661, 391))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(3, 0, 661, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        moduleFlashcards.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(moduleFlashcards)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        moduleFlashcards.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(moduleFlashcards)
        self.statusbar.setObjectName("statusbar")
        moduleFlashcards.setStatusBar(self.statusbar)

        self.retranslateUi(moduleFlashcards)
        QtCore.QMetaObject.connectSlotsByName(moduleFlashcards)

    def retranslateUi(self, moduleFlashcards):
        _translate = QtCore.QCoreApplication.translate
        moduleFlashcards.setWindowTitle(_translate("moduleFlashcards", "moduleFlashcards"))
        self.pushButton.setText(_translate("moduleFlashcards", "Next"))
        self.label.setText(_translate("moduleFlashcards", "Image flash"))
        self.label_2.setText(_translate("moduleFlashcards", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Farsi Text</span></p></body></html>"))
        self.label_3.setText(_translate("moduleFlashcards", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">Pronunciation</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    moduleFlashcards = QtWidgets.QMainWindow()
    ui = UiModuleFlashcards()
    ui.setupUi(moduleFlashcards)
    moduleFlashcards.show()
    sys.exit(app.exec_())
