# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flashcards.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class UiModuleFlashcards(object):
    def setupUi(self, moduleFlashcards):
        moduleFlashcards.setObjectName("moduleFlashcards")
        moduleFlashcards.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(moduleFlashcards)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 500, 83, 25))
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 50, 661, 391))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(120, 0, 431, 271))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(160, 300, 351, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(230, 360, 171, 21))
        self.label_3.setObjectName("label_3")
        moduleFlashcards.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(moduleFlashcards)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        moduleFlashcards.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(moduleFlashcards)
        self.statusbar.setObjectName("statusbar")
        moduleFlashcards.setStatusBar(self.statusbar)

        self.retranslateUi(moduleFlashcards)
        QtCore.QMetaObject.connectSlotsByName(moduleFlashcards)

    def retranslateUi(self, moduleFlashcards):
        _translate = QtCore.QCoreApplication.translate
        moduleFlashcards.setWindowTitle(_translate("moduleFlashcards", "moduleFlashcards"))
        self.pushButton.setText(_translate("moduleFlashcards", "Next"))
        self.label.setText(_translate("moduleFlashcards", "Image flash"))
        self.label_2.setText(_translate("moduleFlashcards", "Farsi Text"))
        self.label_3.setText(_translate("moduleFlashcards", "English text"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    moduleFlashcards = QtWidgets.QMainWindow()
    ui = UiModuleFlashcards()
    ui.setupUi(moduleFlashcards)
    moduleFlashcards.show()
    sys.exit(app.exec_())
