adjectives={
"able" : "قادر است",
"available" : "در دسترس",
"bad" : "بد",
"big" : "بزرگ",
"certain" : "مسلم - قطعی",
"clear" : "روشن",
"different" : "ناهمسان",
"difficult" : "دشوار",
"early" : "زود",
"economic" : "اقتصادی",
"far" : "دور",
"full" : "پر شده",
"general" : "عمومی",
"good" : "خوب",
"great" : "عالی",
"high" : "بالا",
"important" : "مهم",
"international" : "بین المللی",
"large" : "بزرگ",
"last" : "",
"late" : "دیر",
"likely" : "احتمال دارد",
"little" : "مقدار کمی",
"local" : "محلی",
"long" : "طولانی",
"low" : "کم",
"main" : "",
"major" : "عمده",
"national" : "ملی",
"new" : "جدید",
"old" : "قدیمی",
"only" : "فقط",
"other" : "دیگر",
"particular" : "خاص",
"political" : "سیاسی",
"possible" : "ممکن است",
"public" : "عمومی",
"real" : "واقعی",
"right" : "درست",
"small" : "کم اهمیت",
"social" : "اجتماعی",
"special" : "خاص",
"sure" : "مطمئن",
"young" : "جوان",
}
