adjectives={
"able" :["قادر است","ghaa-dar ast"],
"available" :["در دسترس","dar dast-rass"],
"bad" :["بد","bad"],
"big" :["بزرگ","bo-zorg"],
"certain" :[" ‌‌‌قطعی","ghat-ee"],
"clear" :["روشن","ro-shan"],
"different" :["متفاوت","mu-ta-faa-vet"],
"difficult" :["دشوار","dosh-vaar"],
"early" :["زود","zood"],
"economic" :["اقتصادی","egh-te-saa-di"],
"far" :["دور","door"],
"full" :["پر","por"],
"general" :["معمول","ma'-mool"],
"good" :["خوب","khoob"],
"great" :["عالی","aa-li"],
"high" :["بالا","baa-laa"],
"important" :["مهم","mo-hem"],
"international" :["بین المللی","bey-nol-ma-la-li"],
"large" :["بزرگ","bo-zorg"],
"last" :["اخرین","aa-kher-in"],
"late" :["دیر","dir"],
"likely" :["احتمال دارد","eh-te-maal daa-rad"],
"little (amount)" :["مقدار کمی","megh-daar ka-mi"],
"local" :["محلی","ma-ha-li"],
"long" :["طولانی","tu-laa-ni"],
"low" :[" پایین / کم","paa-een / kam"],
"main" :["اصلی","ass-li"],
"major" :["عمده","um-deh"],
"national" :["ملی","me-li"],
"new" :["جدید","ja-did"],
"old" :["قدیمی","gha-di-mi"],
"only" :["فقط","fa-ghat"],
"other" :["دیگر","di-gar"],
"particular/special" :["خاص","khaas"],
"political" :["سیاسی","si-aa-si"],
"possible" :["ممکن است","moom-ken ast"],
"public" :["عمومی","u-mum-i"],
"real" :["واقعی","va-ghe-ii"],
"right" :["درست","do-rost"],
"small" :["کوچک ","ku-chak"],
"social" :["اجتماعی","ej-te-maa-i"],
"special" :["خاص","khaas"],
"sure" :["مطمئن","mut-ma-een"],
"young" :["جوان","ja-vaan"],
}
