adverbs={
"about" : "در باره",
"actually" : "Translation",
"again" : "از نو",
"all" : "Translation",
"almost" : "تقریبا",
"already" : "قبلا، پیش از این",
"also" : "همچنین",
"always" : "همیشه",
"around" : "دور و بر",
"as" : "",
"away" : "دور",
"back" : "بازگشت",
"both" : "هر دو",
"down" : "پایین",
"early" : "زود",
"else" : "دیگر",
"enough" : "کافی",
"even" : "زوج",
"ever" : "همیشه",
"far" : "دور",
"here" : "اینجا",
"how" : "Translation",
"however" : "با این حال",
"in" : "Translation",
"just" : "فقط",
"later" : "بعد",
"least" : "کمترین",
"less" : "کمتر",
"long" : "طولانی",
"more" : "بیشتر",
"most" : "اکثر",
"much" : "بسیار",
"never" : "هرگز",
"next" : "بعد",
"no" : "نه",
"not" : "نه",
"now" : "اکنون",
"off" : "خاموش",
"often" : "غالبا",
"on" : "Translation",
"once" : "یک بار",
"only" : "فقط",
"out" : "بیرون",
"over" : "بر فراز",
"particularly" : "به ویژه",
"perhaps" : "شاید",
"probably" : "شاید",
"quite" : "کاملا",
"quickly" : "به سرعت",
"rather" : "نسبتا",
"really" : "واقعا",
"right" : "درست",
"slowly" : "به آرامی",
"so" : "بنابراین",
"sometimes" : "گاهی",
"soon" : "به زودی",
"still" : "هنوز",
"then" : "سپس",
"there" : "آنجا",
"therefore" : "از این رو",
"today" : "امروز",
"together" : "با یکدیگر",
"too" : "هم",
"up" : "بالا",
"very" : "خیلی",
"well" : "خوب",
"when" : "چه زمانی",
"where" : "جایی که",
"why" : "چرا",
"yet" : "هنوز",
}
