adverbs={
"about" :["در باره","dar baa-reh"],
"actually" :["در واقع","dar waa-gheh"],
"again" :["دوباره ","do-baar-eh"],
"all" :["همه","ham-eh"],
"almost" :["تقریبا","tagh-ri-ban"],
"already" :["قبلا، پیش از این","ghab-lan / pish az een"],
"also" :["همچنین","ham-che-neen"],
"always" :["همیشه","ham-ish-eh"],
"around" :["دور و بر","dor oh bar"],
"as" :["تا","taa"],
"away" :["دور","door"],
"back" :["بازگشت/عقب","baaz-gasht / a-ghab"],
"both" :["هر دو","har doh"],
"down" :["پایین","paa-een"],
"early" :["زود","zood"],
"else" :["دیگر","di-gar"],
"enough" :["کافی","kaa-fee"],
"even" :["زوج","zooj"],
"ever" :["همیشه","ham-ee-sheh"],
"far" :["دور","door"],
"here" :["اینجا","een-jaa"],
"how" :["چطور","che-tor"],
"however" :["با این حال","baa een haal"],
"in" :["در","dar"],
"just" :["فقط","fa-ghat"],
"later" :["بعد","ba'ad"],
"least" :["کمترین","kam-taar-een"],
"less" :["کمتر","kam-tar"],
"long" :["طولانی","too-laa-ni"],
"more" :["بیشتر","bish-taar"],
"most" :["بیشترین","bish-taar-een"],
"much" :["بسیار/خیلی","beh-si-aar / khi-li"],
"never" :["هرگز","har-gez"],
"next" :["بعد","ba'ad"],
"no" :["نه","nah"],
"not" :["نه","nah"],
"now" :["حالا","haa-laa"],
"off" :["خاموش","khaa-moosh"],
"often" :["غالبا","gha-le-ban"],
"on" :["روی","roo-ye"],
"once" :["یک بار","yek baar"],
"only" :["فقط","fa-ghat"],
"out" :["بیرون","bi-roon"],
"over" :["بر فراز","bar far-aaz"],
"particularly" :["به ویژه","beh vi-dzeh"],
"perhaps" :["شاید","shaa-yad"],
"probably" :["شاید","shaa-yad"],
"quite" :["کاملا","kaa-me-lan"],
"quickly" :["به سرعت","beh soor-at"],
"rather" :["نسبتا","nes-ba-tan"],
"really" :["واقعا","vaa-ghan"],
"right" :["درست","do-rost"],
"slowly" :["به آرامی","beh aa-raa-mi"],
"so" :["بنابراین","ban-aa-bar-een"],
"sometimes" :["گاهی","gaa-hi"],
"soon" :["به زودی","beh zoo-di"],
"still" :["هنوز","ha-nooz"],
"then" :["سپس","se-pass"],
"there" :["آنجا","oon-jaa"],
"therefore" :["از این رو","az een roo"],
"today" :["امروز","em-rooz"],
"together" :["با یکدیگر","baa yek-di-gar"],
"too" :["هم","ham"],
"up" :["بالا","baa-laa"],
"very" :["خیلی","khi-li"],
"well" :["خوب","khoob"],
"when" :["چه زمانی","che za-maa-ni"],
"where" :["جایی که","jaa-ee keh"],
"why" :["چرا","che-raa"],
"yet" :["هنوز","ha-nooz"],
}
