articles={
"a" :["یک","yek"],
"all" :["همه","ham-eh"],
"an" :["یک","yek"],
"another" :["یکی دیگر","yek-i di-gar"],
"any" :["هر","har"],
"both" :["هر دو","har do"],
"each" :["هر یک","har yek"],
"every" :["هر","har"],
"half" :["نیم","neem"],
"her" :["مال او","maal-eh oo"],
"his" :["مال او","maal-eh oo"],
"its" :["مال او","maal-eh oo"],
"little" :["مقدار کمی","magh-daar ka-mi"],
"many" :["زیاد","zi-aad"],
"more" :["بیشتر","bish-taar"],
"most" :["بیشترین","bish-taar-een"],
"much" :["بسیار","be-si-aar"],
"my" :["مال من","maal-eh man"],
"next" :["بعد","ba'ad"],
"no" :["نه","nah"],
"our" :["مال ما","maal-eh maa"],
"own" :["خود ","khod"],
"same" :["یکسان","yek-saan"],
"several" :["چندین","chand-een"],
"some" :["مقداری/تعدادی","megh-daa-ri / te'-daa-di"],
"such" :["چنین","che-nin"],
"that" :["آن","oon"],
"the" :["-",""],
"their" :["مال آنها","maal-eh aan-ha"],
"these" :["اینها","een-ha"],
"this" :["این","een"],
"those" :["آن ها","oon-haa"],
"what" :["چه","che"],
"which" :["کدام","ko-doom"],
"your" :["مال شما","maal-eh sho-maa"],
}
