articles={
"a" : "Translation",
"all" : "Translation",
"an" : "Translation",
"another" : "یکی دیگر",
"any" : "هر",
"both" : "هر دو",
"each" : "هر یک",
"every" : "هر",
"half" : "نیم",
"her" : "او",
"his" : "خود",
"its" : "Translation",
"little" : "مقدار کمی",
"many" : "زیاد",
"more" : "بیشتر",
"most" : "اکثر",
"much" : "بسیار",
"my" : "من",
"next" : "بعد",
"no" : "نه",
"our" : "ما",
"own" : "خود را",
"same" : "یکسان",
"several" : "چندین",
"some" : "Translation",
"such" : "چنین",
"that" : "Translation",
"the" : "Translation",
"their" : "Translation",
"these" : "اینها",
"this" : "Translation",
"those" : "آن ها",
"what" : "Translation",
"which" : "Translation",
"your" : "شما",
}
