conjunctions={
"after" :["بعد از","ba'ad aaz"],
"although" :["با اينكه","baa een-keh"],
"and" :[" و","oo"],
"as" :["تا","taa"],
"because" :["چونکه/زیرا","chun-keh / zee-raa"],
"before" :["قبل از","ghab-le aaz"],
"but" :["ولی/اما","va-li / aa-maa"],
"if" :["اگر","a-gar"],
"or" :["یا","yaa"],
"since" :["از آنجا که","aaz oon-ja keh"],
"so" :["بنابراین","ben-aa-bar-een"],
"than" :["نسبت به/ از","nes-bat beh/aaz"],
"that" :["که","keh"],
"though" :["اگر چه","a-gar cheh"],
"until" :["تا زمانی که","taa za-maan-ee keh"],
"when" :["زمانی که","za-maa-ni keh"],
"where" :["جایی که","jaa-ee keh"],
"whether" :["چه","cheh"],
"while" :["در حالی که","dar haa-laa keh"],
}
