conjunctions={
"after" : "بعد از",
"although" : "با اينكه",
"and" : "Translation",
"as" : "",
"because" : "زیرا",
"before" : "قبل از",
"but" : "ولی",
"if" : "اگر",
"or" : "یا",
"since" : "از آنجا که",
"so" : "بنابراین",
"than" : "نسبت به. تا",
"that" : "Translation",
"though" : "اگر چه",
"until" : "تا زمان",
"when" : "چه زمانی",
"where" : "جایی که",
"whether" : "چه",
"while" : "در حالی که",
}
