nouns={
"action" : "عمل",
"activity" : "فعالیت",
"age" : "سن",
"area" : "حوزه",
"authority" : "قدرت",
"back" : "بازگشت",
"bank" : "بانک",
"bird" : "پرنده",
"bit" : "بیت",
"body" : "بدن",
"book" : "",
"boy" : "",
"building" : "ساختمان",
"business" : "کسب و کار",
"butt" : "لب به لب",
"car" : "ماشین",
"case" : "",
"center" : "مرکز",
"century" : "قرن",
"chair" : "صندلی",
"change" : "Translation",
"child" : "کودک",
"church" : "کلیسا",
"city" : "شهر",
"class" : "کلاس",
"committee" : "کمیته",
"community" : "انجمن",
"company" : "شرکت",
"computer" : "کامپیوتر",
"condition" : "شرایط. شرط",
"control" : "کنترل",
"cost" : "هزینه",
"council" : "شورا",
"country" : "کشور",
"course" : "دوره",
"court" : "دادگاه",
"day" : "روز",
"death" : "مرگ",
"decision" : "تصمیم گیری",
"department" : "بخش",
"desk" : "میز مطالعه",
"development" : "توسعه",
"door" : "در، درب",
"education" : "",
"effect" : "اثر",
"end" : "پایان",
"event" : "رویداد",
"evidence" : "شواهد و مدارک",
"example" : "مثال",
"experience" : "تجربه",
"eye" : "چشم",
"face" : "صورت",
"fact" : "حقیقت",
"family" : "خانواده",
"father" : "پدر",
"few" : "تعداد کمی",
"figure" : "شکل",
"finger" : "انگشت",
"food" : "غذا",
"foot" : "پا",
"force" : "زور",
"form" : "",
"friend" : "دوست",
"game" : "بازی",
"girl" : "",
"government" : "دولت",
"ground" : "زمین",
"group" : "گروه",
"hand" : "دست",
"head" : "سر",
"health" : "سلامتی",
"home" : "خانه",
"hour" : "ساعت",
"house" : "خانه",
"idea" : "اندیشه",
"industry" : "صنعت",
"information" : "اطلاعات",
"interest" : "علاقه",
"issue" : "موضوع",
"job" : "کار",
"kind" : "نوع",
"language" : "Translation",
"law" : "قانون",
"letter" : "Translation",
"level" : "مرحله",
"life" : "زندگی",
"line" : "",
"lot" : "مقدار زیادی",
"man" : "مرد",
"management" : "مدیریت",
"market" : "بازار",
"matter" : "موضوع",
"member" : "عضو",
"mind" : "ذهن",
"minister" : "وزیر",
"minute" : "دقیقه",
"moment" : "لحظه",
"money" : "پول",
"month" : "ماه",
"morning" : "صبح",
"mother" : "مادر",
"name" : "Translation",
"need" : "Translation",
"night" : "شب",
"number" : "عدد",
"office" : "دفتر",
"other" : "دیگر",
"paper" : "کاغذ",
"part" : "بخش",
"party" : "مهمانی - جشن",
"patient" : "صبور",
"pen" : "خودکار",
"pencil" : "مداد",
"people" : "مردم",
"percent" : "درصد",
"period" : "عادت زنانه",
"person" : "شخص",
"pin" : "سنجاق",
"place" : "محل",
"plan" : "طرح",
"point" : "نقطه",
"police" : "پلیس",
"policy" : "خط مشی",
"position" : "موقعیت",
"power" : "قدرت",
"practice" : "تمرین",
"price" : "قیمت",
"problem" : "مسئله",
"process" : "روند",
"product" : "تولید - محصول",
"program" : "برنامه",
"question" : "",
"radio" : "رادیو",
"range" : "دامنه",
"rate" : "نرخ",
"reason" : "دلیل",
"report" : "گزارش",
"research" : "پژوهش",
"result" : "نتیجه",
"right" : "درست",
"road" : "جاده",
"role" : "نقش",
"room" : "اتاق",
"school" : "مدرسه",
"section" : "بخش",
"sense" : "احساس، مفهوم",
"service" : "سرویس",
"shoes" : "کفش",
"side" : "",
"society" : "جامعه",
"socks" : "جوراب",
"sort" : "مرتب سازی",
"staff" : "کارکنان",
"state" : "دولت",
"student" : "",
"study" : "مطالعه",
"subject" : "موضوع",
"support" : "پشتیبانی",
"system" : "سیستم",
"table" : "جدول",
"team" : "تیم",
"television" : "تلویزیون",
"term" : "",
"thing" : "چیز",
"time" : "زمان",
"type" : "Translation",
"use" : "استفاده کنید",
"value" : "مقدار",
"view" : "چشم انداز",
"voice" : "صدا",
"war" : "",
"water" : "اب",
"way" : "Translation",
"week" : "هفته",
"woman" : "زن",
"word" : "Translation",
"work" : "کار کردن",
"world" : "جهان",
"year" : "سال",
}
