nouns={
"action" :["عمل","a-mal"],
"activity" :["فعالیت","fal-ee-yat"],
"age" :["سن","sen"],
"area" :["حوزه","ho-zeh"],
"authority" :["قدرت","ghod-rat"],
"back" :[" پشت","posht"],
"bank" :["بانک","bank"],
"bird" :["پرنده","pa-ran-deh"],
"bit" :["کمی","ka-mi"],
"body" :["بدن","ba-dan"],
"book" :["کتاب","ke-taab"],
"boy" :["پسر","pe-sar"],
"building" :["ساختمان","saakh-te-moon"],
"business" :["کسب و کار","kasb o kaar"],
"butt" :["کون","koon"],
"car" :["ماشین","maa-shin"],
"case" :["مورد","moo-red"],
"center" :["مرکز","mar-kaz"],
"century" :["قرن","gharn"],
"chair" :["صندلی","san-daa-li"],
"change" :["تغییر","tagh-yir"],
"child" :["کودک","koo-dak"],
"church" :["کلیسا","ke-li-saa"],
"city" :["شهر","shahr"],
"class" :["کلاس","ke-laas"],
"committee" :["کمیته","ko-mi-teh"],
"community" :["انجمن","an-jo-man"],
"company" :["شرکت","shar-kat"],
"computer" :["کامپیوتر","kom-poo-ter"],
"condition" :["شرایط. شرط","sha-raa-yet / shart"],
"control" :["کنترل","kon-trol"],
"cost" :["هزینه","haz-ee-neh"],
"council" :["شورا","shoo-raa"],
"country" :["کشور","kesh-vaar"],
"course" :["دوره","do-reh"],
"court" :["دادگاه","daad-gaah"],
"day" :["روز","rooz"],
"death" :["مرگ","marg"],
"decision" :["تصمیم گیری","tass-meem gi-ri"],
"department" :["بخش","bakhsh"],
"desk" :["میز مطالعه","miz-eh mu-taa-l'eh"],
"development" :["توسعه","tos'eh"],
"door" :["در ","dar"],
"education"  :["تحصیل","tah-sil"],
"effect" :["اثر","a-sar"],
"end" :["پایان","paa-yaan"],
"event" :["رویداد","rui-daad"],
"evidence" :[" مدارک","ma-daa-rek"],
"example" :["مثال","mass-aal"],
"experience" :["تجربه","taj-ro-beh"],
"eye" :["چشم","cheshm"],
"face" :["صورت","soo-rat"],
"fact" :["حقیقت","ha-ghi-ghat"],
"family" :["خانواده","khaa-ne-vaa-deh"],
"father" :["پدر","pe-dar"],
"few" :["تعداد کمی","ta'daad-eh ka-mi"],
"figure" :["شکل","shekl"],
"finger" :["انگشت","ang-gosht"],
"food" :["غذا","gha-za"],
"foot" :["پا","paa"],
"force" :["زور","zoor"],
"form" :["شکل","shekl"],
"friend" :["دوست","doost"],
"game" :["بازی","baa-zi"],
"girl" :["دختر","dokh-tar"],
"government" :["دولت","dow-lat"],
"ground" :["زمین","za-min"],
"group" :["گروه","grooh"],
"hand" :["دست","dast"],
"head" :["سر","sar"],
"health" :["سلامتی","salaamati"],
"home" :["خانه","khoo-neh"],
"hour" :["ساعت","saa-a't"],
"house" :["خانه","khoo-neh"],
"idea" :["ایده","ee-deh"],
"industry" :["صنعت","san-a't"],
"information" :["اطلاعات","eh-ta-laa-'aat"],
"interest" :["علاقه","a-laa-gheh"],
"issue" :["موضوع","mow-zoo'"],
"job" :["کار","kaar"],
"kind" :["نوع","noo'"],
"language" :["زبان","za-boon"],
"law" :["قانون","ghaa-noon"],
"letter" :["نامه","naa-meh"],
"level" :["مرحله","mar-hal-eh"],
"life" :["زندگی","zen-di-gi"],
"line" :["خط","khat"],
"a lot (amount)" :["مقدار زیادی","magh-daar-eh zee-aa-di"],
"man" :["مرد","mard"],
"management" :["مدیریت","mo-di-ri-yat"],
"market" :["بازار","baa-zaar"],
"matter" :["موضوع","moo-zoo'eh"],
"member" :["عضو","ozv"],
"mind" :["ذهن","zeh-n"],
"minister" :["وزیر","va-zir"],
"minute" :["دقیقه","da-ghi-gheh"],
"moment" :["لحظه","lah-zeh"],
"money" :["پول","pul"],
"month" :["ماه","maah"],
"morning" :["صبح","sobh"],
"mother" :["مادر","maa-dar"],
"name" :["اسم/نام","esm / naam"],
"need" :["نیاز","ni-az"],
"night" :["شب","shab"],
"number" :["عدد","a-dad"],
"office" :["دفتر","daf-tar"],
"other" :["دیگر","di-gar"],
"paper" :["کاغذ","kaa-ghaz"],
"part" :["بخش","bakhsh"],
"party" :["مهمانی - جشن","meh-moo-ni / jashn"],
"patient" :["مریض","mariz"],
"pen" :["خودکار","khod-kaar"],
"pencil" :["مداد","me-daad"],
"people" :["مردم","mar-dum"],
"percent" :["درصد","dar-sad"],
"period" :["مرحله ","mar-hal-eh"],
"person" :["شخص","shakhs"],
"pin" :["سنجاق","sen-jaagh"],
"place" :["محل","mahal"],
"plan" :["طرح /برنامه","tarh / bar-naa-meh"],
"point" :["نقطه","nogh-teh"],
"police" :["پلیس","po-lis"],
"policy" :["خط مشی/سیاست","khat-e mash-i / si-aa-sat"],
"position" :["موقعیت","moo-ghay-yat"],
"power" :["قدرت","ghad-rat"],
"practice" :["تمرین","tam-rin"],
"price" :["قیمت","ghi-mat"],
"problem" :["مسئله","mosh-kel-h"],
"process" :["روند","ra-vand"],
"product" :["تولید/ محصول","tow-lid / mah-sool"],
"program" :["برنامه","bar-naa-meh"],
"question" :["سوال","so-al"],
"radio" :["رادیو","raa-di-o"],
"range" :["دامنه","daa-man-eh"],
"rate" :["نرخ","narkh"],
"reason" :["دلیل","da-lil"],
"report" :["گزارش","go-zaa-resh"],
"research" :["تحقیق/پژوهش","tah-ghigh / pa-dzoo-hesh"],
"result" :["نتیجه","na-ti-jeh"],
"right" :["درست","do-rost"],
"road" :["جاده","jaa-deh"],
"role" :["نقش","naghsh"],
"room" :["اتاق","o-taagh"],
"school" :["مدرسه","mad-re-seh"],
"section" :["بخش","bakhsh"],
"sense" :["احساس/ مفهوم","eh-saas / maf-hoom"],
"service" :["سرویس","ser-vis"],
"shoes" :["کفش","kafsh"],
"side" :["طرف","ta-raf"],
"society" :["جامعه","jaam-'eh"],
"socks" :["جوراب","joo-rab"],
"sort" :["گونه/نوع","goon-eh / nogh"],
"staff" :["کارکنان","kaar-ko-naan"],
"state" :["دولت/حالت","dow-lat / haa-lat"],
"student" :["دانش آموز","daa-nesh aa-muz"],
"study" :["مطالعه","moo-taa-l'eh"],
"subject" :["موضوع","moo-zoogh"],
"support" :["پشتیبانی","pash-ti-baa-ni"],
"system" :["سیستم","sis-tem"],
"table" :["جدول","jaad-val"],
"team" :["تیم","teem"],
"television" :["تلویزیون","te-le-vi-zion"],
"term" :["ترم","term"],
"thing" :["چیز","chiz"],
"time" :["زمان","za-maan"],
"type" :["گونه/نوع","goon-eh / nogh"],
"use" :["استفاده","es-te-faa-deh"],
"value" :["ارزش","ar-zesh"],
"view" :["چشم انداز","cheshm aan-daaz"],
"voice" :["صدا","se-daa"],
"war" :["جنگ","jang"],
"water" :["اب","aab"],
"way" :["راه","raah"],
"week" :["هفته","hafteh"],
"woman" :["زن","zan"],
"word" :["کلمه","ke-la-meh"],
"work" :["کار ","kaar"],
"world" :["جهان","ja-haan"],
"year" :["سال","saal"],
}
