prepositions={
"about" :["در باره","dar baa-reh"],
"across" :["ان سو","aan soo"],
"after" :["بعد از","bad az"],
"against" :["در برابر","dar bar-aa-bar"],
"among" :["در میان","dar mi-aan"],
"around" :["دور و بر","dor-o-bar"],
"as (similar to)" :["مانند","maa-nand"],
"at" :["در","dar"],
"before" :["قبل از","ghabl az"],
"behind" :["پشت","posht"],
"beside" :["در کنار","dar ken-aar"],
"between" :["بین","beyn"],
"by" :["توسط","ta-va-sot"],
"during" :["در حین","dar heyn"],
"for" :["برای","ba-raa-ye"],
"from" :["از","az"],
"in" :["در","dar"],
"including" :["شامل","shaa-mel"],
"into" :["داخل","daa-khel"],
"like" :["شبیه","shabih"],
"of" :["از","az"],
"out" :["بیرون","bi-run"],
"on" :["روی","ru-ye"],
"over" :["بر فراز","bar far-aaz"],
"through" :["از سمت","az samt"],
"to" :["به","beh"],
"towards" :["به سمت","beh samt"],
"under" :["زیر","zir"],
"underneath" :["در زیر","dar zir"],
"upon" :["بر","bar"],
"with" :["با","baa"],
"within" :["در داخل","dar daa-khel"],
"without" :["بدون","be-du-ne"],
}
