prepositions={
"about" : "در باره",
"across" : "در سراسر",
"after" : "بعد از",
"against" : "در برابر",
"among" : "در میان",
"around" : "دور و بر",
"as" : "مانند",
"at" : "Translation",
"before" : "قبل از",
"behind" : "پشت",
"beside" : "در کنار",
"between" : "بین",
"by" : "توسط",
"during" : "در حین",
"for" : "Translation",
"from" : "Translation",
"in" : "Translation",
"including" : "شامل",
"into" : "Translation",
"like" : "Translation",
"of" : "Translation",
"off" : "خاموش",
"on" : "Translation",
"over" : "بر فراز",
"through" : "از طریق",
"to" : "Translation",
"towards" : "به سمت",
"under" : "زیر",
"underneath" : "در زیر",
"upon" : "بر",
"with" : "Translation",
"within" : "در داخل",
"without" : "بدون",
}
