pronouns={
"anything" :["هر چیزی","har chi-zi"],
"he" :["او","oo"],
"her" :["او","oo"],
"him" :["او","oo"],
"himself" :["خودش","khodesh"],
"I" :["من","man"],
"it" :["آن","oon"],
"itself" :["خودش","khodesh"],
"me" :["من","man"],
"nothing" :["هیچ چیزی","hich chi-zi"],
"one" :["یکی","yeki"],
"she" :["او","oo"],
"something" :["چیزی","chi-zi"],
"them" :["آنها","on-ha"],
"themselves" :["خودشان","khod-esh-oon"],
"there" :["آنجا","oon-ja"],
"they" :["آنها","on-ha"],
"us" :["ما","ma"],
"we" :["ما","ma"],
"who" :["کسی","ka-see"],
"you" :["شما","sho-ma"],
}
