pronouns={
"anything" : "هر چیزی",
"he" : "Translation",
"her" : "او",
"him" : "به او",
"himself" : "خودش",
"I" : "Translation",
"it" : "Translation",
"itself" : "خود",
"me" : "Translation",
"nothing" : "هیچ چیزی",
"one" : "یکی",
"she" : "Translation",
"something" : "چیزی",
"them" : "آنها",
"themselves" : "خودشان",
"there" : "آنجا",
"they" : "Translation",
"us" : "ما",
"we" : "Translation",
"who" : "سازمان بهداشت جهانی",
"you" : "شما",
}
