verbs={
"to add" :["اضافه کردن","ezaa-feh kardan"],
"to agree" :["موافقت کردن","mu-va-fe-ghat kardan"],
"to allow" :["اجازه دادن","eh-jaa-zeh daa-dan"],
"to appear" :["ظاهر شدن","zaa-hair shodan"],
"to ask" :["پرسیدن","por-see-dan"],
"to be" :["بودن","boo-dan"],
"to become" :["شدن","sho-dan"],
"to begin" :["شروع کردن","shu-ru' kardan"],
"to believe" :["باور كردن","baa-var kardan"],
"to bring" :["آوردن","aa-var-dan"],
"to build" :["ساختن","saakh-tan"],
"to buy" :["خریدن","kha-ri-dan"],
"to call" :["صدا کردن/زنگ زدن","zang zadan/se-daa kardan"],
"to carry" :[" حمل کردن","haml kardan"],
"to change" :["تغییر دادن","tagh-yiir daadan"],
"to come" :["آمدن","aa-ma-dan"],
"to consider" :["در نظر گرفتن","dar nazar gereftan"],
"to continue" :["ادامه دادن","eh-daa-meh daadan"],
"to create" :["خلق كردن","khalgh kardan"],
"to decide" :["تصمیم گرفتن","tas-meem gereftan"],
"to describe" :[" توصیف کردن","to-seef kardan"],
"to develop" :["توسعه دادن","to-se-eh daadan"],
"to die" :[" مردن","mor-dan"],
"to do" :["انجام دادن","an-jaam daadan"],
"to draw" :["کشیدن","kesh-i-dan"],
"to expect" :["توقع داشتن","ta-va-gho dash-tan"],
"to fall" :["افتادن","of-taa-dan"],
"to feel" :["حس کردن","hess kardan"],
"to find" :[" پیدا کردن","pey-daa kardan"],
"to follow" :["پيگيري كردن","pey-gi-ri kardan"],
"to get" :[" بدست آوردن","beh-dast avardan"],
"to give" :["دادن","daa-dan"],
"to go" :["رفتن","raftan"],
"to happen" :["اتفاق افتادن","eh-te-faagh of-ta-dan"],
"to have" :["داشتن","daash-tan"],
"to hear" :["شنیدن","shenidan"],
"to help" :[" کمک کردن","kumak kardan"],
"to hold" :["نگه داشتن","ne-gah daashtan"],
"to hope" :[" امید داشتن","omid daashtan"],
"to include" :["شامل شدن","shaa-mel shodan"],
"to increase" :[" افزایش دادن","af-zaa-yesh daa-dan"],
"to involve" :["دربرگرفتن - شامل کردن/شامل شدن","shaa-mel shodan/kardan - darbar gereftan"],
"to keep" :[" نگه داشتن","ne-gah daashtan"],
"to know" :["دانستن","daa-nes-tan"],
"to lead" :["هدایت کردن","hed-aa-yat kardan"],
"to learn" :["یاد گرفتن ","yaad gereftan"],
"to leave" :["ترك كردن","tark kardan"],
"to let" :["اجازه دادن","eh-jaa-zeh daadan"],
"to lie" :["دروغ گفتن","dor-oogh goftan"],
"to like" :["دوست داشتن","doost dashtan"],
"to live" :["  زندگی کردن","zendigi kardan"],
"to look" :["نگاه كردن","negaah kardan"],
"to lose" :["از دست دادن","az dast daa-dan"],
"to make" :["ساختن","saakhtan"],
"to mean" :["معنی دادن","mani daadan"],
"to meet" :[" ملاقات کردن","mulaa-ghaat kardan"],
"to move" :["حرکت کردن","har-kat kardan"],
"to need" :["نیاز داشتن","ni-aaz dashtan"],
"to offer" :["پیشنهاد دادن","pish-na-haad daa-dan"],
"to open" :["بازکردن","baaz-kardan"],
"to pay" :["   پرداخت کردن","par-daakht kardan"],
"to play" :["بازی کردن","baazi kardan"],
"to produce" :[" تولید کردن","to-lid kardan"],
"to provide" :["فراهم كردن","far-aa-ham kardan"],
"to put" :["گذاشتن","goz-aash-tan"],
"to reach" :[" رسیدن ","res-i-dan"],
"to read" :["خواندن","khaan-dan"],
"to receive" :[" دریافت کردن","dar-yaaft kardan"],
"to remain" :["باقی ماندن","baa-ghi maan-dan"],
"to remember" :["به یاد اوردن","beh yaad aa-var-dan"],
"to report" :["گزارش کردن","goz-aa-resh kardan"],
"to require" :["نیاز داشتن ","niaaz daashtan"],
"to return" :["برگشتن","bar-gash-tan"],
"to run" :["اجرا کردن /دویدن","davidan/ej-raa kardan"],
"to say" :["گفتن","goftan"],
"to see" :["دیدن","di-dan"],
"to seem" :["به نظر رسیدن","beh na-zar residan"],
"to sell" :["فروختن","for-ookh-tan"],
"to send" :["فرستادن","fer-es-taa-dan"],
"to set" :["تنظیم کردن","tan-zeem kardan"],
"to show" :["نشان دادن","ne-shaan daa-dan"],
"to sit" :["نشستن","neshastan"],
"to speak" :["صحبت کردن","soh-bat kardan"],
"to spend" :["خرج كردن","kharj kardan"],
"to stand" :["ایستادن","is-taa-dan"],
"to start" :["  شروع کردن","sho-ruu kardan"],
"to stop" :[" متوقف کردن","mu-te-va-ghef kardan"],
"to suggest" :["پیشنهاد دادن","pish-na-haad daadan"],
"to take" :["گرفتن","gereftan"],
"to talk" :["صحبت کردن","soh-bat kardan"],
"to tell" :["گفتن","goftan"],
"to think" :["فکر کردن","fekr kardan"],
"to try" :[" امتحان کردن","em-te-haan kardan"],
"to turn" :["چرخیدن","char-khi-dan"],
"to understand" :["فهمیدن","fah-mi-dan"],
"to use" :[" استفاده کردن","es-te-faa-deh kardan"],
"to walk" :["راه رفتن","raah raftan"],
"to want" :["خواستن","khaas-tan"],
"to win" :["برنده شدن","baran-deh shodan"],
"to work" :[" کار کردن","kaar kardan"],
"to write" :["نوشتن","ne-vesh-tan"],
}
