verbs={
"to add" :["اضافه کردن","ezaa-feh kardan"],
"to agree" :["موافقت کردن","mu-va-fe-ghat kardan"],
"to allow" :["اجازه دادن","eh-jaa-zeh daa-dan"],
"to appear" :["ظاهر شدن","zaa-hair shodan"],
"to ask" :["پرسیدن","por-see-dan"],
"to be" :["بودن","boo-dan"],
"to become" :["شدن","sho-dan"],
"to begin" :["شروع کردن","shu-ru' kardan"],
"to believe" :["باور كردن","baa-var kardan"],
"to bring" :["آوردن","aa-var-dan"],
"to build" :["ساختن","saakh-tan"],
"to buy" :["خریدن","kha-ri-dan"],
"to call" :["صدا کردن/زنگ زدن","zang zadan/se-daa kardan"],
"to carry" :[" حمل کردن","haml kardan"],
"to change" :["تغییر دادن","tagh-yiir daadan"],
"to come" :["آمدن","aa-ma-dan"],
"to consider" :["در نظر گرفتن","dar nazar gereftan"],
"to continue" :["ادامه دادن","eh-daa-meh daadan"],
"to create" :["خلق كردن","khalgh kardan"],
"to decide" :["تصمیم گرفتن","tas-meem gereftan"],
"to describe" :[" توصیف کردن","to-seef kardan"],
"to develop" :["توسعه دادن","to-se-eh daadan"],
"to die" :[" مردن","mor-dan"],
"to do" :["انجام دادن","an-jaam daadan"],
"to draw" :["کشیدن","kesh-i-dan"],
"to expect" :["توقع داشتن","ta-va-gho dash-tan"],
"to fall" :["افتادن","of-taa-dan"],
"to feel" :["حس کردن","hess kardan"],
"to find" :[" پیدا کردن","pey-daa kardan"],
"to follow" :["پيگيري كردن","pey-gi-ri kardan"],
"to get" :[" بدست آوردن","beh-dast avardan"],
"to give" :["دادن","daa-dan"],
"to go" :["رفتن","raftan"],
"to happen" :["اتفاق افتادن","eh-te-faagh of-ta-dan"],
"to have" :["داشتن","daash-tan"],
"to hear" :["شنیدن","shenidan"],
"to help" :[" کمک کردن","kumak kardan"],
"to hold" :["نگه داشتن","ne-gah daashtan"],
"to hope" :[" امید داشتن","omid daashtan"],
"to include" :["شامل شدن","shaa-mel shodan"],
"to increase" :[" افزایش دادن","af-zaa-yesh daa-dan"],
"to involve" :["دربرگرفتن - شامل کردن/شامل شدن","shaa-mel shodan/kardan - darbar gereftan"],
"to keep" :[" نگه داشتن","ne-gah daashtan"],
"to know" :["دانستن","daa-nes-tan"],
"to lead" :["هدایت کردن","hed-aa-yat kardan"],
"to learn" :["یاد گرفتن ","yaad gereftan"],
"to leave" :["ترك كردن","tark kardan"],
"to let" :["اجازه دادن","eh-jaa-zeh daadan"],
"to lie" :["دروغ گفتن","dor-oogh goftan"],
"to like" :["دوست داشتن","doost dashtan"],
"to live" :["  زندگی کردن","zendigi kardan"],
"to look" :["نگاه كردن","negaah kardan"],
"to lose" :["از دست دادن","az dast daa-dan"],
"to make" :["ساختن","saakhtan"],
"to mean" :["معنی دادن","mani daadan"],
"to meet" :[" ملاقات کردن","mulaa-ghaat kardan"],
"to move" :["حرکت کردن","har-kat kardan"],
"to need" :["نیاز داشتن","ni-aaz dashtan"],
"to offer" :["پیشنهاد دادن","pish-na-haad daa-dan"],
"to open" :["بازکردن","baaz-kardan"],
"to pay" :["   پرداخت کردن","par-daakht kardan"],
"to play" :["بازی کردن","baazi kardan"],
"to produce" :[" تولید کردن","to-lid kardan"],
"to provide" :["فراهم كردن","far-aa-ham kardan"],
"to put" :["گذاشتن","goz-aash-tan"],
"to reach" :[" رسیدن ",""],
"to read" :["خواندن",""],
"to receive" :[" دریافت کردن",""],
"to remain" :["باقی ماندن",""],
"to remember" :["به یاد اوردن",""],
"to report" :["گزارش کردن",""],
"to require" :["نیاز داشتن ",""],
"to return" :["برگشتن",""],
"to run" :["اجرا کردن /دویدن",""],
"to say" :["گفتن",""],
"to see" :["دیدن",""],
"to seem" :["به نظر رسیدن",""],
"to sell" :["فروختن",""],
"to send" :["فرستادن",""],
"to set" :["تنظیم کردن",""],
"to show" :["نشان دادن",""],
"to sit" :["نشستن",""],
"to speak" :["صحبت کردن",""],
"to spend" :["خرج كردن",""],
"to stand" :["ایستادن",""],
"to start" :["  شروع کردن",""],
"to stop" :[" متوقف کردن",""],
"to suggest" :["پیشنهاد دادن",""],
"to take" :["گرفتن",""],
"to talk" :["صحبت کردن",""],
"to tell" :["گفتن",""],
"to think" :["فکر کردن",""],
"to try" :[" امتحان کردن",""],
"to turn" :["چرخیدن",""],
"to understand" :["فهمیدن",""],
"to use" :[" استفاده کردن",""],
"to walk" :["راه رفتن",""],
"to want" :["خواستن",""],
"to win" :["برنده شدن",""],
"to work" :[" کار کردن",""],
"to write" :["نوشتن",""],
}
