verbs={
"to add" : "برای اضافه کردن",
"to agree" : "برای موافقت",
"to allow" : "اجازه دادن",
"to appear" : "ظاهر شدن",
"to ask" : "پرسیدن",
"to be" : "بودن",
"to become" : "شدن",
"to begin" : "برای شروع",
"to believe" : "باور كردن",
"to bring" : "آوردن",
"to build" : "ساختن",
"to buy" : "خریدن",
"to call" : "Translation",
"to carry" : "برای حمل",
"to change" : "Translation",
"to come" : "آمدن",
"to consider" : "در نظر گرفتن",
"to continue" : "ادامه",
"to create" : "خلق كردن",
"to decide" : "برای تصمیم گیری",
"to describe" : "برای توصیف",
"to develop" : "توسعه دهد",
"to die" : "برای مردن",
"to do" : "انجام دادن",
"to draw" : "کشیدن",
"to expect" : "توقع داشتن",
"to fall" : "افتادن",
"to feel" : "حس کردن",
"to find" : "برای پیدا کردن",
"to follow" : "پيگيري كردن",
"to get" : "برای بدست آوردن",
"to give" : "دادن",
"to go" : "رفتن",
"to happen" : "اتفاق افتادن",
"to have" : "داشتن",
"to hear" : "شنیدن",
"to help" : "برای کمک به",
"to hold" : "نگه داشتن",
"to hope" : "به امید",
"to include" : "شامل شدن",
"to increase" : "برای افزایش",
"to involve" : "دربرگرفتن - شامل بودن - شامل شدن",
"to keep" : "برای نگه داشتن",
"to know" : "دانستن",
"to lead" : "هدایت کردن",
"to learn" : "برای یادگیری",
"to leave" : "ترك كردن",
"to let" : "اجازه دادن",
"to lie" : "دروغ گفتن",
"to like" : "",
"to live" : "برای زندگی",
"to look" : "نگاه كردن",
"to lose" : "از دست دادن",
"to make" : "ساختن",
"to mean" : "Translation",
"to meet" : "برای ملاقات",
"to move" : "حرکت کردن",
"to need" : "Translation",
"to offer" : "پیشنهاد دادن",
"to open" : "بازکردن",
"to pay" : "برای پرداخت",
"to play" : "بازی کردن",
"to produce" : "برای تولید",
"to provide" : "فراهم كردن",
"to put" : "گذاشتن",
"to reach" : "برای رسیدن به",
"to read" : "خواندن",
"to receive" : "برای دریافت",
"to remain" : "باقی ماندن",
"to remember" : "به خاطر سپردن",
"to report" : "گزارش کردن",
"to require" : "نیاز داشته باشد",
"to return" : "برگشتن",
"to run" : "برای اجرا",
"to say" : "Translation",
"to see" : "دیدن",
"to seem" : "به نظر می رسد",
"to sell" : "فروختن",
"to send" : "فرستادن",
"to set" : "تنظیم کردن",
"to show" : "",
"to sit" : "نشستن",
"to speak" : "سخن گفتن",
"to spend" : "خرج كردن",
"to stand" : "ایستادن",
"to start" : "برای شروع",
"to stop" : "برای متوقف کردن",
"to suggest" : "حدس زدن",
"to take" : "گرفتن",
"to talk" : "صحبت کردن",
"to tell" : "Translation",
"to think" : "فکر کردن",
"to try" : "برای امتحان",
"to turn" : "چرخیدن",
"to understand" : "فهمیدن",
"to use" : "برای استفاده",
"to walk" : "راه رفتن",
"to want" : "خواستن",
"to win" : "برنده شدن",
"to work" : "برای کار",
"to write" : "Translation",
}
